### PR TITLE
Laravel package 2.0.0 + alpha ordering sdks/integrations

### PR DESCRIPTION
**Pull request by clemblanco**
* Updated `laravel.md` with latest docs from version `2.0.0`
* Moved it back into SDK for consistency: sorry I was wrong saying it is a "Package", it technically is but it fits better with the other SDKs in the documentation as this is where you'd be looking for it as a developer imo
* SDK References are alphabetically ordered in the overview page
* Sidebar alphabetically ordered
    * SDK References are alphabetically ordered in the sidebar
    * Integrations are alphabetically ordered in the sidebar
* Homepage SDKs alphabetically ordered
* Added Deno community SDK back in
    
Don't forget to update the homepage links to SDKs too. :v:

### CODE REVIEW

**Comment by sigewuzhere** [comment]
> * Updated `laravel.md` with latest docs from version `2.0.0`
:+1: 

> * Moved it back into SDK for consistency: sorry I was wrong saying it is a "Package", it technically is but it fits better with the other SDKs in the documentation as this is where you'd be looking for it as a developer IMO

It was a conscious decision to keep the community packages separated from the official ones.

> * SDK References are alphabetically ordered in the overview page
> * Sidebar alphabetically ordered
>  * SDK References are alphabetically ordered in the sidebar
>   * Integrations are alphabetically ordered in the sidebar

The ordering should be by popularity.

> Don't forget about [#224 (comment)](https://github.com/configcat/docs/pull/224#issuecomment-1443928271)

It's on PR. ;)

**Comment by sigewuzhere** [comment]
We'll discuss this with the team and figure out way to how to organize the docs. :wink:

**Comment by sigewuzhere** [comment]
Hi @clemblanco

- The alphabetical order is approved by the team.
- The `community maintained` folder should be a subfolder of the `SDK references` folder, so it is visible that those are separate packages that still belong to the SDK references. Is it okay with you?

**Comment by sigewuzhere** [comment]
Okay, I can imagine something like: 
Laravel (Community maintained) if it fits in one line, or just Laravel (Community)

**Comment by sigewuzhere** [comment]
Works for me ;)

**Review by sigewuzhere — APPROVED** [review]
Looks good to me. Double checking with the team.

**Review by z4kn4fein — APPROVED** [review]

**Comment by sigewuzhere** [comment]
Merged! Thank you very much for the contribution!

**Pull request merged**
